# Generated Terraform Configuration
# Resource Type: aws_vpc
# Generated by PACE InfraFlow Manager

resource "aws_vpc" "abzooba_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "10.1.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name = "Abzooba-VPC"
  }
}

resource "aws_vpc" "dagility_sandbox_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "10.97.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name = "DAgility-Sandbox-VPC"
  }
}

resource "aws_vpc" "default_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "172.31.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name = "Default VPC"
  }
}

resource "aws_vpc" "edgeops_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "10.0.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name = "EdgeOps-VPC"
  }
}

resource "aws_vpc" "eks_kubecon_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "172.21.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name                                = "eks-kubecon-VPC"
    "kubernetes.io/cluster/eks-kubecon" = "shared"
  }
}

resource "aws_vpc" "eks_secure_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "172.20.0.0/16"
  enable_dns_hostnames                 = false
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name                               = "eks-secure-VPC"
    "kubernetes.io/cluster/eks-secure" = "shared"
  }
}

resource "aws_vpc" "ekshelmvpcstack_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "192.168.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name                                       = "Ekshelmvpcstack-VPC"
    "kubernetes.io/cluster/Edgeopshelmcluster" = "shared"
  }
}

resource "aws_vpc" "gitlift_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "10.0.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Environment = "test"
    Name        = "gitlift-vpc"
  }
}

resource "aws_vpc" "test_cluster_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "10.0.0.0/16"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name = "test-cluster-vpc"
  }
}

resource "aws_vpc" "ust_practice_vpc" {
  assign_generated_ipv6_cidr_block     = false
  cidr_block                           = "10.2.0.0/24"
  enable_dns_hostnames                 = true
  enable_dns_support                   = true
  enable_network_address_usage_metrics = false
  instance_tenancy                     = "default"
  ipv4_ipam_pool_id                    = null
  ipv4_netmask_length                  = null
  ipv6_ipam_pool_id                    = null
  region                               = "us-east-1"
  tags = {
    Name                            = "UST Practice"
    "kubernetes.io/cluster/QDB-EKS" = "shared"
  }
}
