# Generated Terraform Configuration
# Resource Type: aws_vpc_endpoint
# Generated by PACE InfraFlow Manager

resource "aws_vpc_endpoint" "poc_s3_endpoint" {
  auto_accept     = null
  ip_address_type = "ipv4"
  policy = jsonencode({
    Statement = [{
      Action    = "*"
      Effect    = "Allow"
      Principal = "*"
      Resource  = "*"
    }]
    Version = "2008-10-17"
  })
  private_dns_enabled        = false
  region                     = "us-east-1"
  resource_configuration_arn = null
  route_table_ids            = ["rtb-d7a3d6b1"]
  security_group_ids         = []
  service_name               = "com.amazonaws.us-east-1.s3"
  service_network_arn        = null
  service_region             = "us-east-1"
  subnet_ids                 = []
  tags = {
    Name = "poc-s3-endpoint"
  }
  vpc_endpoint_type = "Gateway"
  vpc_id            = "vpc-03cfc064"
  dns_options {
    dns_record_ip_type                             = "service-defined"
    private_dns_only_for_inbound_resolver_endpoint = false
  }
}

resource "aws_vpc_endpoint" "vpce_eks" {
  auto_accept     = null
  ip_address_type = "ipv4"
  policy = jsonencode({
    Statement = [{
      Action    = "*"
      Effect    = "Allow"
      Principal = "*"
      Resource  = "*"
    }]
    Version = "2008-10-17"
  })
  private_dns_enabled        = false
  region                     = "us-east-1"
  resource_configuration_arn = null
  route_table_ids            = ["rtb-0518f151647c0b7cf"]
  security_group_ids         = []
  service_name               = "com.amazonaws.us-east-1.s3"
  service_network_arn        = null
  service_region             = "us-east-1"
  subnet_ids                 = []
  tags = {
    Name = "VPCE-EKS"
  }
  vpc_endpoint_type = "Gateway"
  vpc_id            = "vpc-03faa642e5ca94a2d"
  dns_options {
    dns_record_ip_type                             = "service-defined"
    private_dns_only_for_inbound_resolver_endpoint = false
  }
}

resource "aws_vpc_endpoint" "vpce_s3_eks_secure" {
  auto_accept     = null
  ip_address_type = "ipv4"
  policy = jsonencode({
    Statement = [{
      Action    = "*"
      Effect    = "Allow"
      Principal = "*"
      Resource  = "*"
    }]
    Version = "2008-10-17"
  })
  private_dns_enabled        = false
  region                     = "us-east-1"
  resource_configuration_arn = null
  route_table_ids            = ["rtb-07810fc4c8c41b001", "rtb-07bd51d45aae250fb", "rtb-0aa7929daa51d3686"]
  security_group_ids         = []
  service_name               = "com.amazonaws.us-east-1.s3"
  service_network_arn        = null
  service_region             = "us-east-1"
  subnet_ids                 = []
  tags = {
    Name = "VPCE-S3-eks-secure"
  }
  vpc_endpoint_type = "Gateway"
  vpc_id            = "vpc-0e4d2c5a50cb2a7e5"
  dns_options {
    dns_record_ip_type                             = "service-defined"
    private_dns_only_for_inbound_resolver_endpoint = false
  }
}
