# Generated Terraform Configuration
# Resource Type: aws_workspaces_workspace
# Generated by PACE InfraFlow Manager

resource "aws_workspaces_workspace" "workspace_ust_ann_satheesh" {
  bundle_id                      = "wsb-g5rbnq51n"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-ann-satheesh"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "STANDARD"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 60
    user_volume_size_gib                      = 50
  }
}

resource "aws_workspaces_workspace" "workspace_ust_ayush_jasrotia" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-ayush-jasrotia"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 180
    user_volume_size_gib                      = 50
  }
}

resource "aws_workspaces_workspace" "workspace_ust_chirag_khandel" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-chirag-khandel"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 180
    user_volume_size_gib                      = 100
  }
}

resource "aws_workspaces_workspace" "workspace_ust_darshana" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-darshana"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 240
    user_volume_size_gib                      = 100
  }
}

resource "aws_workspaces_workspace" "workspace_ust_divya_mantri" {
  bundle_id                      = "wsb-g5rbnq51n"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  tags = {
    createdby = "sujith.esurendran@ust.com"
  }
  user_name                      = "ust-divya-mantri"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "STANDARD"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 240
    user_volume_size_gib                      = 50
  }
}

resource "aws_workspaces_workspace" "workspace_ust_goutham" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-goutham"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "POWER"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 60
    user_volume_size_gib                      = 100
  }
}

resource "aws_workspaces_workspace" "workspace_ust_hydra_team" {
  bundle_id                      = "wsb-397hxf1ww"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = true
  user_name                      = "ust-hydra-team"
  user_volume_encryption_enabled = true
  volume_encryption_key          = "arn:aws:kms:us-east-1:682452625784:key/3cb2a2d3-2d4a-41dc-84e5-262bedef2a12"
  workspace_properties {
    compute_type_name                         = "POWER"
    root_volume_size_gib                      = 400
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 180
    user_volume_size_gib                      = 300
  }
}

resource "aws_workspaces_workspace" "workspace_ust_kaushal_darji" {
  bundle_id                      = "wsb-g5rbnq51n"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-kaushal-darji"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "STANDARD"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 60
    user_volume_size_gib                      = 50
  }
}

resource "aws_workspaces_workspace" "workspace_ust_mahesh_ingle" {
  bundle_id                      = "wsb-g5rbnq51n"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-mahesh-ingle"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 60
    user_volume_size_gib                      = 50
  }
}

resource "aws_workspaces_workspace" "workspace_ust_manu" {
  bundle_id                      = "wsb-397hxf1ww"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-manu"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "POWER"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 240
    user_volume_size_gib                      = 50
  }
}

resource "aws_workspaces_workspace" "workspace_ust_minnu_antony" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-minnu-antony"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 180
    user_volume_size_gib                      = 50
  }
}

resource "aws_workspaces_workspace" "workspace_ust_parashuram" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-parashuram"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 240
    user_volume_size_gib                      = 100
  }
}

resource "aws_workspaces_workspace" "workspace_ust_samit_singh" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-samit-singh"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 180
    user_volume_size_gib                      = 50
  }
}

resource "aws_workspaces_workspace" "workspace_ust_sujith_surendran" {
  bundle_id                      = "wsb-397hxf1ww"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = true
  user_name                      = "ust-sujith-surendran"
  user_volume_encryption_enabled = true
  volume_encryption_key          = "arn:aws:kms:us-east-1:682452625784:key/3cb2a2d3-2d4a-41dc-84e5-262bedef2a12"
  workspace_properties {
    compute_type_name                         = "POWER"
    root_volume_size_gib                      = 300
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 240
    user_volume_size_gib                      = 200
  }
}

resource "aws_workspaces_workspace" "workspace_ust_vishnu_sasi" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-vishnu-sasi"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 120
    user_volume_size_gib                      = 100
  }
}

resource "aws_workspaces_workspace" "workspace_ust_will_sebastian" {
  bundle_id                      = "wsb-208l8k46h"
  directory_id                   = "d-9067993615"
  region                         = "us-east-1"
  root_volume_encryption_enabled = false
  user_name                      = "ust-will-sebastian"
  user_volume_encryption_enabled = false
  volume_encryption_key          = null
  workspace_properties {
    compute_type_name                         = "PERFORMANCE"
    root_volume_size_gib                      = 80
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 180
    user_volume_size_gib                      = 50
  }
}
